AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a Lambda function that can be invoked by CodePipeline to invalidate CloudFront Distribution
Transform: AWS::Serverless-2016-10-31
Resources:
  CreateLambdaExecutionPolicy:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        ManagedPolicyName: Lambda_Cloudfront_Invalidation
        Description: "Policy to invalidate Cloudfront Distribution called inside a CodePipeline"
        Path: "/"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: VisualEditor0
              Effect: Allow
              Action: cloudfront:CreateInvalidation
              Resource: '*'
            - Sid: VisualEditor1
              Effect: Allow
              Action: [
                'codepipeline:PutJobSuccessResult',
                'codepipeline:PutJobFailureResult'
              ]
              Resource: '*'
            - Sid: VisualEditor2
              Effect: Allow
              Action: logs:*
              Resource: '*'
  LambdaExecutedRole:
    Type: 'AWS::IAM::Role'
    Properties:
      ManagedPolicyArns: [
        !Ref CreateLambdaExecutionPolicy
      ]
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com"
      Path: /
      RoleName: LambdaExecutedRole_Invalidate
  LambdaCloudfrontInvalidation:
    DeletionPolicy: Retain
    Type: AWS::Serverless::Function
    Properties:
      Handler: invalidateCloudFront.lambda_handler
      Role:
        Fn::GetAtt:
          - "LambdaExecutedRole"
          - "Arn"
      CodeUri: s3://cloudformation-public.starters.run/invalidateCloudFront.zip
      Runtime: "python2.7"
      Timeout: 25
  LambdaVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName:
        Ref: LambdaCloudfrontInvalidation
      Description: v1
Outputs:
  LambdaCloudFrontInvalidationName:
    Description: Lambda function name
    Value:
      Ref: LambdaCloudfrontInvalidation
  LambdaCloudfrontInvalidationVersion:
    Description: Lambda function and version ARN
    Value:
      Ref: LambdaVersion