# https://aws.amazon.com/blogs/security/how-to-use-aws-certificate-manager-with-aws-cloudformation/
AWSTemplateFormatVersion: 2010-09-09
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Domain
      Parameters:
      - SubDomain
      - DomainName
      - HostedZoneId
Mappings:
  Solution:
    Constants:
      Version: v0.5
Parameters:
  SubDomain:
    Description: A secondary subdomain to be covered by this certificate. Use '*' for wildcard to cover all subdomains.
    Type: String
    Default: "*"
    AllowedPattern: ^[^.]*$
  DomainName:
    Description: The domain name of your Route53 hosted zone.
    Type: String
  HostedZoneId:
    Description: The id of your Route53 hosted zone.
    Type: String
Resources:
  ACMCertificate: 
      Type: "AWS::CertificateManager::Certificate"
      Properties: 
        DomainName:
          Ref: DomainName
        SubjectAlternativeNames:
        - Fn::Sub: ${SubDomain}.${DomainName}
        DomainValidationOptions:
        - DomainName: 
            Ref: DomainName
          HostedZoneId:
            Ref: HostedZoneId
        ValidationMethod: DNS
Outputs:
  CertificateArn:
    Description: Issued certificate
    Value:
      Ref: ACMCertificate