AWSTemplateFormatVersion: '2010-09-09'
Description: ACFS3 - CloudFront with Header Security and site content
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaEdgeFunction:
    DeletionPolicy: Retain
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Role:
        Fn::GetAtt:
        - LambdaEdgeFunctionRole
        - Arn
      CodeUri: s3://cloudformation-public.us-east-1.starters.run/LambdaEdgeFunction-d76d09f0f8d899b4ef68bb0caeb4ed1b.zip
      Runtime: nodejs12.x
      Timeout: 25
  LambdaVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName:
        Ref: LambdaEdgeFunction
      Description: v1
  LambdaEdgeFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AllowLambdaServiceToAssumeRole
          Effect: Allow
          Action:
          - sts:AssumeRole
          Principal:
            Service:
            - lambda.amazonaws.com
            - edgelambda.amazonaws.com
      Tags:
      - Key: Solution
        Value: ACFS3
Outputs:
  LambdaEdgeFunctionVersion:
    Description: Security Lambda version
    Value:
      Ref: LambdaVersion
