AWSTemplateFormatVersion: '2010-09-09'
Description: Secure S3 Website
Transform: AWS::Serverless-2016-10-31
Resources:
  S3BucketLogs:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: LogDeliveryWrite
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      Tags:
      - Key: Solution
        Value: ACFS3
  S3BucketRoot:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName:
          Ref: S3BucketLogs
        LogFilePrefix: origin/
      Tags:
      - Key: Solution
        Value: ACFS3
Outputs:
  S3BucketRoot:
    Description: Website bucket
    Value:
      Ref: S3BucketRoot
  S3BucketRootName:
    Description: Website bucket name
    Value:
      Fn::GetAtt:
      - S3BucketRoot
      - DomainName
  S3BucketRootArn:
    Description: Website bucket locator
    Value:
      Fn::GetAtt:
      - S3BucketRoot
      - Arn
  S3BucketLogs:
    Description: Logging bucket
    Value:
      Ref: S3BucketLogs
  S3BucketLogsName:
    Description: Logging bucket Name
    Value:
      Fn::GetAtt:
      - S3BucketLogs
      - DomainName