# https://github.com/aws-samples/amazon-cloudfront-secure-static-site
AWSTemplateFormatVersion: 2010-09-09
Description: Creates ACM Certificate and Lambda Edge Function that are required to be in us-east-1 region.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Domain
      Parameters:
      - DomainName
      - HostedZoneId
      - CertificateArn
    - Label:
        default: GitHub
      Parameters:
      - GitHubOAuthToken
      - GitHubOwner
      - GitHubRepo
      - GitHubBranch
    - Label: 
        default: Other
      Parameters:
      - LambdaEdgeArn
Mappings:
  Solution:
    Constants:
      Version: v0.5
Parameters:
  DomainName:
    Description: The part of a website address after your SubDomain - e.g. example.com
    Type: String
  HostedZoneId:
    Description: The id of your Route53 hosted zone.
    Type: String
  CertificateArn:
    Description: The ARN of the ACM SSL Certificate (must be in us-east-1 region)
    Type: String
  GitHubOAuthToken:
    Type: String
    NoEcho: true
    MinLength: 40
    MaxLength: 40
    AllowedPattern: '[a-z0-9]*'
    Description: With this Token a Webhook will be created for the repo
  GitHubOwner:
    Type: String
    AllowedPattern: "[A-Za-z0-9-]+"
    Description: The Owner of the GitHub Repo
  GitHubRepo:
    Description: GitHub Repo
    Type: String
  GitHubBranch:
    Type: String
    Default: main
    AllowedPattern: "[A-Za-z0-9-]+"
    Description: The name of the GitHub Repo Branch which should be used
  LambdaEdgeArn:
    Description: The ARN of the Lambda@Edge function with adds response security headers (must be in us-east-1 region)
    Type: String
Resources:
  S3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cloudformation-public.starters.run/s3.yml
  CloudFront:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cloudformation-public.starters.run/cloudfront.yml
      Parameters:
        CertificateArn:
          Ref: CertificateArn
        DomainName:
          Ref: DomainName
        HostedZoneId:
          Ref: HostedZoneId
        S3BucketLogs:
          Fn::GetAtt:
          - S3
          - Outputs.S3BucketLogs
        S3BucketRoot:
          Fn::GetAtt:
          - S3
          - Outputs.S3BucketRoot
        S3BucketLogsName:
          Fn::GetAtt:
          - S3
          - Outputs.S3BucketLogsName
        S3BucketRootName:
          Fn::GetAtt:
          - S3
          - Outputs.S3BucketRootName
        S3BucketRootArn:
          Fn::GetAtt:
          - S3
          - Outputs.S3BucketRootArn
        LambdaVersion:
          Ref: LambdaEdgeArn
  CloudFrontInvalidationLambda:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cloudformation-public.starters.run/cloudfront-invalidation-lambda.yml
  CodePipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cloudformation-public.starters.run/codepipeline.yml
      Parameters:
        GitHubOAuthToken:
          Ref: GitHubOAuthToken
        GitHubOwner:
          Ref: GitHubOwner
        GitHubRepo:
          Ref: GitHubRepo
        GitHubBranch:
          Ref: GitHubBranch
        TargetS3Bucket:
          Fn::GetAtt:
          - S3
          - Outputs.S3BucketRoot
        CloudFrontDistributionId:
          Fn::GetAtt:
          - CloudFront
          - Outputs.CloudFrontDistributionId
        CloudFrontInvalidationLambdaName:
          Fn::GetAtt:
          - CloudFrontInvalidationLambda
          - Outputs.LambdaCloudFrontInvalidationName
Outputs:
  S3BucketRoot:
    Description: ARN of Origin Bucket
    Value:
      Fn::GetAtt:
      - S3
      - Outputs.S3BucketRoot
  S3BucketLogs:
    Description: ARN of Access Logs
    Value:
      Fn::GetAtt:
      - S3
      - Outputs.S3BucketLogs
  CloudFrontDistributionId:
    Description: Distribution Id of CloudFront CDN
    Value:
      Fn::GetAtt:
      - CloudFront
      - Outputs.CloudFrontDistributionId
  CloudFrontInvalidationLambda:
    Description: Lambda function and version ARN
    Value:
      Fn::GetAtt:
        - CloudFrontInvalidationLambda
        - Outputs.LambdaCloudfrontInvalidationVersion
  CodePipeline:
    Description: ARN of CodePipeline
    Value:
      Fn::GetAtt:
        - CodePipeline
        - Outputs.CodePipelineARN
  
  
