# https://github.com/aws-samples/amazon-cloudfront-secure-static-site
AWSTemplateFormatVersion: 2010-09-09
Description: Creates ACM Certificate and Lambda Edge Function that are required to be in us-east-1 region.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Domain
      Parameters:
      - SubDomain
      - DomainName
      - HostedZoneId
Mappings:
  Solution:
    Constants:
      Version: v0.5
Parameters:
  SubDomain:
    Description: A secondary subdomain to be covered by this certificate. Use '*' for wildcard to cover all subdomains.
    Type: String
    Default: "*"
    AllowedPattern: ^[^.]*$
  DomainName:
    Description: The part of a website address after your SubDomain - e.g. example.com
    Type: String
  HostedZoneId:
    Description: The id of your Route53 hosted zone.
    Type: String
Resources:
  AcmCertificateStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cloudformation-public.us-east-1.starters.run/acm-public-certificate.us-east-1.yml
      Parameters:
        SubDomain:
          Ref: SubDomain
        DomainName:
          Ref: DomainName
        HostedZoneId:
          Ref: HostedZoneId
  LambdaEdgeFunction:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cloudformation-public.us-east-1.starters.run/lambda-edge.us-east-1.yml
Outputs:
  CertificateArn:
    Description: Issued certificate
    Value:
      Fn::GetAtt:
      - AcmCertificateStack
      - Outputs.CertificateArn
  LambdaEdgeFunctionVersion:
    Description: Security Lambda version
    Value:
      Fn::GetAtt:
      - LambdaEdgeFunction
      - Outputs.LambdaEdgeFunctionVersion
